services:
  - type: web
    name: wanderquest-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: wanderquest-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://your-vercel-domain.vercel.app

databases:
  - name: wanderquest-db
    plan: free
    databaseName: wanderquest
    user: wanderquest_user
